#!/bin/bash

# Store arguments relevant to Squirrel
runtime=0
args=""
while [[ $# -gt 0 ]]; do
        case $1 in
                --time)
                        runtime=$2
                        shift
                        ;;
                *)
                        args=$args" "$1
                        ;;
        esac
        shift
done
# Submit
python -m cli submit "$args" $runtime