version: '3'

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    hostname: influxdb
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    ports:
      - "8086:8086"
    networks:
      - squirrel
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./influxv2.env
    networks:
      - squirrel

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  squirrel:
    driver: bridge
